apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-node
spec:
  replicas: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
        app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
      - name: argocd-node
        image: ramazancetin/node-app:0.1
        ports:
        - containerPort: 8005
