apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml
images:
- name: ramazancetin/node-app
  newTag: cc4b5a8e6f33bedb83c1cd8c1586f0e21f386e32
