apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: node
  name: argocd-node
spec:
  ports:
  - port: 8005
    protocol: TCP
    targetPort: 8005
    nodePort: 30001
  selector:
    app: argocd-demo
  type: NodePort
status:
  loadBalancer: {}
