apiVersion: v1
kind: Service
metadata:
  name:  argocd-node
spec:
  selector:
    app:  argocd-node
  type:  LoadBalancer
  ports:
  - port:  8005
    targetPort:  8005
    nodePort: 30000
  externalIPs:
  - 51.15.137.75
